# Configuration file for wine_quality_pipeline

data:
  raw_path: "data/raw/winequality.csv"
  processed_path: "data/processed/processed_winequality.csv"

model:
  test_size: 0.2
  random_state: 42
  model_type: "RandomForestRegressor"  # can be extended to other models
  n_estimators: 100

mlflow:
  tracking_uri: "file:./mlruns"  # local mlruns folder

deployment:
  host: "0.0.0.0"
  port: 8000